name: sefii_flutter_x
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_custom_clippers: ^1.1.0
  provider: ^3.1.0 
  google_maps_flutter: ^0.5.21+15
  date_picker_timeline: ^1.1.3
  card_settings: ^1.5.3
  image_picker: ^0.6.2+3
  add_2_calendar: ^1.3.1
  awesome_dialog: ^0.1.0
  flutter_calendar: ^0.0.9
  pin_code_fields: 2.3.0+3
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  intl: ^0.16.1
  image: ^2.1.12
  progress_dialog: ^1.2.0


# dev_dependencies:
#   flutter_test:
#     sdk: flutter


flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
  assets:
    - assets/map_style.json
  uses-material-design: true
